import './globals.css'
import Navigation from './nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen flex flex-col ">
          <Navigation />
          <div className="container">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
